# 配置启动端口
server:
  port: 7001

# eureka 注册中心配置
eureka:
  instance:
    # eureka 服务器的实例名称
    hostname: localhost
  client:
    # false 表示不向注册中心注册自己
    register-with-eureka: false
    # false 表示自己就是注册中心，只负责维护服务实例，并不检索服务
    fetch-registry: false
    # 设置与 EurekaServer 交互的地址查询服务和注册服务都需要依赖这个地址
    service-url: http://${eureka.instance.hostname}:${server.port}/eureka/
